[build]
  base = "/"  # Set the build directory to the client folder
  command = "npm run client-build"  # Build the React frontend
  publish = "client/build"  # Publish the React build output

# Netlify Development Server Settings
[dev]
  framework = "create-react-app"
  command = "npm run dev"  # Start both Express backend & React frontend
  targetPort = 3000  # Set to the Express server port
  autoLaunch = true
  port = 8000  # Netlify local dev server port

[functions]
  directory = "netlify/functions"  # Path to Netlify serverless functions (if used)

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  force = true
