[build]
  command = "npm run build --prefix client"
  publish = "client/build"
  
[[redirects]]
  from = "/*"
  to = "/server"
  status = 200

[build.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-sitemap"
