[build]
  base = "."  # Build from the root directory
  publish = "client/build"  # Publish the React build folder
  command = "npm run build --prefix client"  # Build React app


[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  force = false


[functions]  
  directory = "netlify/functions"  # Express backend functions


[dev]
  command = "nodemon server/app.js"  # Run Express backend during dev
  targetPort = 8000  # Express backend will run on port 8000
  port = 8888  # Netlify serves frontend here
  publish = "client/build"  # Serve React frontend