[build]
  command = "npm run build --prefix client"  # Add --prefix client to run the build script inside the client folder
  publish = "client/build"                   # Make sure this points to the React build folder

[[redirects]]
  from = "/*"
  to = "/server/*"
  status = 200