[build]
  base = "/"  # Set the build directory to the server folder
  publish = "client/build"  # Publish the React build output
  command = "npm run client-build"  # Build the React frontend


[dev]

  command = "npm run dev"  # Start backend & frontend together
  targetPort = 8000  # Express backend runs on 8000
  port = 8888
  autoLaunch = false  # Prevents browser auto-launch


[functions]
  directory = "netlify/functions"  # Location of Netlify functions (if used)


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
