[build]
  base = "."  # Build from the root directory
  publish = "client/build"  # Publish the React build folder
  command = "npm run build --prefix client"  # Build React app
 
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[functions]  
  directory = "netlify/functions"  # Express backend functions