[build]
  base = "/"  # Set the build directory to the server folder
  command = "npm run client-build"  # Build the React frontend
  publish = "client/build"  # Publish the React build output


[dev]
  framework = "create-react-app"
  command = "node app.js"  # Start my server  
  targetPort = 8000
  autoLaunch = false


[functions]
  directory = "netlify/functions"  # Path to Netlify serverless functions (if used)


[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
