[build]
  base = "."  # Build from the root directory
  publish = "client/build"  # Publish the React build folder
  command = "npm run build --prefix client"  # Build React app

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions/function"  # Express backend functions
