[build]
  command = "npm run build --prefix client"
  publish = "client/build"
  
[[redirects]]
  from = "/*"
  to = "/server"
  status = 200

[[headers]]
  for = "/client/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  NODE_ENV = "production"   #deploy-preview, branch

[build.processing]
  html = { minify = true }
  css = { minify = true }
  js = { minify = true, transpile = true }

[[plugins]]
  package = "@netlify/plugin-sitemap"
