[build]
  base = "."  # Build from the root directory
  publish = "client/build"  # Publish the React build folder
  command = "npm run build --prefix client"  # Build React app

[[build.environment]]
  MY_API_KEY = 9889 8888 9049 2341 0987

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"  # Express backend functions
