[build]
  base = "."  # Build from the root directory
  publish = "client/build"  # Publish the React build folder
  command = "npm run build --prefix client"  # Build React app

[[redirects]]
  from = "https://samuelakinolafoundation.netlify.app"
  to = "/index.html"
  status = 200
  force = false

[functions]
  directory = "netlify/functions"  # Express backend functions
