[build]
  base = "server"  # Set the build directory to the server folder
  publish = "server/client/build"  # Publish the React build output
  command = "npm run build --prefix server/client"  # Build the React frontend


[dev]
  framework = "#custom"  # Prevents Netlify from auto-detecting
  command = "npm run dev"  # Start backend & frontend together
  targetPort = 8000  # Express backend runs on 8000
  autoLaunch = false  # Prevents browser auto-launch


[functions]
  directory = "server/netlify/functions"  # Location of Netlify functions (if used)


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200